ST77XX_MOD_DIR := $(USERMOD_DIR)
SRC_USERMOD += $(addprefix $(ST77XX_MOD_DIR)/, \
	st77xx.c \
)
CFLAGS_USERMOD += -I$(ST77XX_MOD_DIR) -DMODULE_ST77XX_ENABLED=1
# CFLAGS_USERMOD += -DST77XX_EXPOSE_EXTRA_METHODS=1
